/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellCoursesRouteImport } from './routes/_shell.courses'
import { Route as ShellCoursesIdRouteImport } from './routes/_shell.courses.$id'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCoursesRoute = ShellCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCoursesIdRoute = ShellCoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShellCoursesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/courses': typeof ShellCoursesRouteWithChildren
  '/courses/$id': typeof ShellCoursesIdRoute
}
export interface FileRoutesByTo {
  '/courses': typeof ShellCoursesRouteWithChildren
  '/': typeof ShellIndexRoute
  '/courses/$id': typeof ShellCoursesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/courses': typeof ShellCoursesRouteWithChildren
  '/_shell/': typeof ShellIndexRoute
  '/_shell/courses/$id': typeof ShellCoursesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/courses' | '/courses/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/courses' | '/' | '/courses/$id'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/courses'
    | '/_shell/'
    | '/_shell/courses/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/courses': {
      id: '/_shell/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof ShellCoursesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/courses/$id': {
      id: '/_shell/courses/$id'
      path: '/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof ShellCoursesIdRouteImport
      parentRoute: typeof ShellCoursesRoute
    }
  }
}

interface ShellCoursesRouteChildren {
  ShellCoursesIdRoute: typeof ShellCoursesIdRoute
}

const ShellCoursesRouteChildren: ShellCoursesRouteChildren = {
  ShellCoursesIdRoute: ShellCoursesIdRoute,
}

const ShellCoursesRouteWithChildren = ShellCoursesRoute._addFileChildren(
  ShellCoursesRouteChildren,
)

interface ShellRouteChildren {
  ShellCoursesRoute: typeof ShellCoursesRouteWithChildren
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellCoursesRoute: ShellCoursesRouteWithChildren,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
